//------------------------ html ------------------------
$("#hbtn1").click(function(e){
    $(".hday1").slideToggle(200);
    $(this).toggleClass("open");
});
$("#hbtn2").click(function(e){
    $(".hday2").slideToggle(200);
    $(this).toggleClass("open");
});
$("#hbtn3").click(function(e){
    $(".hday3").slideToggle(200);
    $(this).toggleClass("open");
});
$("#hbtn4").click(function(e){
    $(".hday4").slideToggle(200);
    $(this).toggleClass("open");
});
$("#hbtn5").click(function(e){
    $(".hday5").slideToggle(200);
    $(this).toggleClass("open");
});
$("#hbtn6").click(function(e){
    $(".hday6").slideToggle(200);
    $(this).toggleClass("open");
});
$("#hbtn7").click(function(e){
    $(".hday7").slideToggle(200);
    $(this).toggleClass("open");
});
$("#hbtn8").click(function(e){
    $(".hday8").slideToggle(200);
    $(this).toggleClass("open");
});
$("#hbtn9").click(function(e){
    $(".hday9").slideToggle(200);
    $(this).toggleClass("open");
});
$("#hbtn10").click(function(e){
    $(".hday10").slideToggle(200);
    $(this).toggleClass("open");
});

//------------------------ css ------------------------
$("#cbtn1").click(function(e){
    $(".cday1").slideToggle(200);
    $(this).toggleClass("open");
});
$("#cbtn2").click(function(e){
    $(".cday2").slideToggle(200);
    $(this).toggleClass("open");
});
$("#cbtn3").click(function(e){
    $(".cday3").slideToggle(200);
    $(this).toggleClass("open");
});
$("#cbtn4").click(function(e){
    $(".cday4").slideToggle(200);
    $(this).toggleClass("open");
});
$("#cbtn5").click(function(e){
    $(".cday5").slideToggle(200);
    $(this).toggleClass("open");
});
$("#cbtn6").click(function(e){
    $(".cday6").slideToggle(200);
    $(this).toggleClass("open");
});
$("#cbtn7").click(function(e){
    $(".cday7").slideToggle(200);
    $(this).toggleClass("open");
});
$("#cbtn8").click(function(e){
    $(".cday8").slideToggle(200);
    $(this).toggleClass("open");
});
$("#cbtn9").click(function(e){
    $(".cday9").slideToggle(200);
    $(this).toggleClass("open");
});
$("#cbtn10").click(function(e){
    $(".cday10").slideToggle(200);
    $(this).toggleClass("open");
});
$("#cbtn11").click(function(e){
    $(".cday11").slideToggle(200);
    $(this).toggleClass("open");
});
$("#cbtn12").click(function(e){
    $(".cday12").slideToggle(200);
    $(this).toggleClass("open");
});
$("#cbtn13").click(function(e){
    $(".cday13").slideToggle(200);
    $(this).toggleClass("open");
});
$("#cbtn14").click(function(e){
    $(".cday14").slideToggle(200);
    $(this).toggleClass("open");
});

//------------------------ script ------------------------
$("#js1").click(function(e){
    $(".jsday1").slideToggle(200);
    $(this).toggleClass("open");
});
$("#js2").click(function(e){
    $(".jsday2").slideToggle(200);
    $(this).toggleClass("open");
});
$("#js3").click(function(e){
    $(".jsday3").slideToggle(200);
    $(this).toggleClass("open");
});
$("#js4").click(function(e){
    $(".jsday4").slideToggle(200);
    $(this).toggleClass("open");
});



